config/routes.rb
SampleApp::Application.routes.draw do
  
  resources :users

  root to: 'static_pages#home'

  match 'signup', to: 'users#new'
  match 'help', to: 'static_pages#help'
  match 'about', to: 'static_pages#about'
  match 'contact', to: 'static_pages#contact'

end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessible :name, :email, :password, :password_confirmation
	has_secure_password

	before_save { |user| user.email = email.downcase }


	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX}, 
					uniqueness: { case_sensitive: false}

	validates :password, presence: true, length: { minimum: 6 }
	validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
  	@user = User.find(params[:id])
  end

  def new
  	@user = User.new
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Ruby on Rails Sample App"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	#returns Gravitron
	def gravatar_for(user)
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
	<div class="navbar-inner">
		<div class ="container">
			<%= link_to "sample app", root_path, id:"logo" %>
			<nav>
				<ul class="nav pull-right">
					<li><%= link_to "Home", root_path %></li>
					<li><%= link_to "Help", help_path %></li>
					<li><%= link_to "Sign in", '#' %></li>
				</ul>
			</nav>
		</div>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title (yield (:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>
	<div class="container">
		<%= yield %>
		<%= render 'layouts/footer' %>
		<%= debug(params) if Rails.env.development? %>
	</div>
	
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<h1>Contact Us</h1>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>

<h1>Help</h1>

app/views/static_pages/home.html.erb
<div class="center hero-unit">
<h1>Sample App</h1>

<h2>
	This is the home page for the
	<a href="http://www.huffingtonpost.com/">Ruby on Rails Tutorial</a>
	sample application.
</h2>

<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %>
</div>

<%= link_to image_tag("rails.png", alt:"Rails"), 'http://rubyonrails.org/' %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>
<div class="row">
	<div class="span6 offset3">
		<%= form_for(@user) do |f| %>

		<%= f.label :name %>
		<%= f.text_field :name %>

		<%= f.label :email %>
		<%= f.text_field :email %>

		<%= f.label :password %>
		<%= f.text_field :password %>

		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.text_field :password_confirmation %>

		<%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

		<% end %>
	</div>
</div>